- package.json
This PR updates react-native version to ^0.4
I tested it with an existing app and did not see any issues.
> update react-native to 0.4.0

- index.js
> handle horizontal swipe only. fixes #4

- README.md
- index.js
Saw the request here - https://github.com/Kureev/react-native-side-menu/issues/1 and since I was already in the code for my previous pull request, I thought why not ;) 
Let me know if this is implemented the way you wanted it.
> Add toggle menu functionality

- README.md
- index.js
Hello,
I found myself in a situation where I wanted to open the sidebar whenever I fire a certain event. This PR adds that kind of functionality. 
Secondly, I added the option to disable gestures for opening the sidebar (for example when moving around in a MapView). I am not 100% sure if using `componentWillReceiveProps` for creating the responders is the right thing to do :tongue:
> Allow menu to open programmatically and option to disable gestures

- index.js
https://github.com/Kureev/react-native-side-menu/issues/17
> Update responders on new props whenever possible.

- index.js
as requested, here's the pull request. issue #19.
> removed unused bind

- animations.js
I have tested my sample code with the given changes proposed by @bright-sea and its cool. Also solves #27
> Changes proposed to remove the createConfig error

- index.js
This is a fixed for issue #26 and it might related to issue #30.
> corrected the logic to handle ScrollView and ListView

- index.js
I have added a little bit of code to get this feature to work. So I added `onChange` props which will be called once Side Menu component closes or opens. I think it is useful for some scenarios. see #23
> added onChange prop to SideMenu component.

- README.md
- index.js
pretty simple approach, let me know what you think.
> adds menuPosition prop, so menu can be used on the right side

- index.js
Should be shouldOpen instead of shouldMenuOpen.
> Fixing typo in `handlePanResponderEnd`

- index.js
Sorry about the typo @Kureev. My bad. I should have caught it in testing.
> Fixing touchToClose PropType typo

- README.md
...with info about touchToClose and updated onChange function
> Update component props in README

- index.js
> fixed #41 forceUpdate moved to a proper location

- package.json
Updates the project version in order to be possible getting this latest version via `npm install`
> Updates version to 0.8.4

- index.js
- styles.js
based on https://github.com/facebook/react-native/issues/2031#issuecomment-122684864
closes #69
> fix orientation

- .gitignore
- README.md
- index.js
* edgeHitWidth can now be passed as prop value
* added WebStorm (IntelliJ) IDE folder to .gitignore
* Adjusted README file
> Added possibility to configure edgeHitWidth

- README.md
- index.js
> Setting default open possible

- README.md
- index.js
Fixes #154. Based on original work in #162
> Implement bounceBackOnOverdraw

- index.js
Adding @noflow makes flow happy without having to make sure all the annotations are actually correct
> Flow annotations are now not allowed in non-flow files

- examples/Basic/Basic.js
- examples/Basic/Menu.js
> Demo closing menu on item tap

- index.js
also fixes initial AnimatedValue for left when menuPosition == 'right.
> fixes menu boundaries when menuPosition == 'right'

- index.js
- package.json
Added React as a dev dep and changed to use component from react rather than react-native
> Fix for ReactNative 0.25+

- index.js
Fixed width, height, openMenuOffset and hiddenMenuOffset on onLayoutChange.
> Landscape Mode (after rotating)

- README.md
> Added table for props - Cleaner look imo

- README.md
- index.js
I have added a utility function onSliding(percentage:number).
This function will be called when the side menu is sliding, it will return a percentage number. The number represents the percent of sliding animation completed by the side menu.
@Kureev Please review the PR and provide any feedbacks. I will happy to update the docs as well.
> Added onSliding function

- README.md
The image on README seems to be no longer available.
I'm not sure what photo was originally used, but I replaced it with a screen capture of running example project.
| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ✅❌     |
| Android |    ✅❌     |
> chore: update README photo
